#!/usr/bin/env perl

use v5.10;
use strict;
use warnings;

use ModuleResolver;

my $module_name = $ARGV[0] or die "Usage: $0 module_name";

my $resolver = ModuleResolver->new;
my $deps = $resolver->get_deps_for($module_name);
use Data::Dumper;
print 'apt-get install -y ' . join ' ', $deps->os_package_list, "\n";

